// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TractorEcommerce.Modules.Sales.Infrastructure.Persistence;

#nullable disable

namespace TractorEcommerce.Modules.Sales.Infrastructure.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    partial class SalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TractorEcommerce.Modules.Sales.Domain.Entities.Cart", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UserId");

                    b.ToTable("carts", "sales");
                });

            modelBuilder.Entity("TractorEcommerce.Modules.Sales.Domain.Entities.Cart", b =>
                {
                    b.OwnsMany("TractorEcommerce.Modules.Sales.Domain.Entities.CartItem", "Items", b1 =>
                        {
                            b1.Property<string>("cart_user_id")
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("VariantId")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Image")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<decimal>("Price")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("ProductId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.Property<string>("VariantName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("cart_user_id", "VariantId");

                            b1.ToTable("cart_items", "sales");

                            b1.WithOwner()
                                .HasForeignKey("cart_user_id");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
