// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TractorEcommerce.Modules.Catalog.Infrastructure.Persistence;

#nullable disable

namespace TractorEcommerce.Modules.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260524015840_AddStoresTable")]
    partial class AddStoresTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TractorEcommerce.Modules.Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EnginePower")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<string[]>("Highlights")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("products", "catalog");

                    b.HasData(
                        new
                        {
                            Id = "tx-001",
                            Brand = "TractorCorp",
                            Category = "autonomous",
                            Description = "Premium autonomous driving tractor.",
                            EnginePower = "240 HP",
                            Highlights = new[] { "GPS Guided Autonomous System", "240 HP High-Performance Power", "Dynamic Torque Control & Field Optimization", "Full Warranty & physical maintenance support included" },
                            Image = "https://placehold.co/600x400/png?text=Autonomous+Titan",
                            Name = "Autonomous Titan",
                            Price = 85000m
                        },
                        new
                        {
                            Id = "tx-002",
                            Brand = "HeritageIron",
                            Category = "classics",
                            Description = "Beautifully restored post-war utility tractor.",
                            EnginePower = "45 HP",
                            Highlights = new[] { "Standard High-Performance Power", "Full Warranty & physical maintenance support included" },
                            Image = "https://placehold.co/600x400/png?text=Classic+Vintage",
                            Name = "Classic Vintage 1950",
                            Price = 45000m
                        });
                });

            modelBuilder.Entity("TractorEcommerce.Modules.Catalog.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("product_id")
                        .HasColumnType("text");

                    b.HasKey("Sku");

                    b.HasIndex("product_id");

                    b.ToTable("product_variants", "catalog");

                    b.HasData(
                        new
                        {
                            Sku = "TX-001-GPS",
                            ProductId = "tx-001",
                            Stock = 8,
                            name = "GPS Edition",
                            product_id = "tx-001"
                        },
                        new
                        {
                            Sku = "TX-001-AI",
                            ProductId = "tx-001",
                            Stock = 3,
                            name = "AI Edition",
                            product_id = "tx-001"
                        },
                        new
                        {
                            Sku = "TX-CLS-01",
                            ProductId = "tx-002",
                            Stock = 0,
                            name = "Standard Edition",
                            product_id = "tx-002"
                        });
                });

            modelBuilder.Entity("TractorEcommerce.Modules.Catalog.Domain.Entities.Store", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("stores", "catalog");

                    b.HasData(
                        new
                        {
                            Id = "store-central",
                            Address = "Av. de la Maquinaria 404",
                            City = "Madrid",
                            Image = "https://placehold.co/300x200",
                            Name = "Central Headquarters"
                        },
                        new
                        {
                            Id = "store-north",
                            Address = "Industrial Route 66, Km 12",
                            City = "Burgos",
                            Image = "https://placehold.co/300x200",
                            Name = "North Hub"
                        });
                });

            modelBuilder.Entity("TractorEcommerce.Modules.Catalog.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("TractorEcommerce.Modules.Catalog.Domain.Entities.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TractorEcommerce.Modules.Catalog.Domain.Entities.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
